name: Download and Package Python Package

on:
  workflow_dispatch:
    inputs:
      packageName:
        description: 'Python package name'
        required: true
        default: 'requests'
      packageVersion:
        description: 'Python package version'
        required: true
        default: '2.31.0'

jobs:
  download-and-package:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install package
        run: |
          python -m pip install --upgrade pip
          pip install ${{ github.event.inputs.packageName }}==${{ github.event.inputs.packageVersion }} --target=package

      - name: Create zip archive
        run: |
          Compress-Archive -Path package/* -DestinationPath package.zip

      - name: Upload package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.packageName }}-${{ github.event.inputs.packageVersion }}-windows-amd64
          path: package.zip
